public/rate-progress.html
public/review-progress.html
public/styles/_add-goal.scss
public/styles/_landing-page.scss
public/styles/_review-progress.scss
public/styles/rate-progress.scss

Review page redesign

---

public/add-goal.html
public/js/index.js
public/styles/_add-goal.scss
public/styles/_colors.scss

Add goal fun improvements

---

public/styles/sass/_review-progress.scss

fix missing background on goal divs

---

index.html

resolves #47 
@shiryz @bradreeder @des-des please take a look and merge if you're around. It's just some changes to the copy requested by our PO! : )

Changes copy

---

.gitignore

Modifies .gitignore to push branch

---

app/app.jsx
app/components/goals-list/goals-list.jsx
app/containers/main.jsx
app/main.js
package.json

@des-des I made this just so that you can see what I've changed so far (compared to last PR)
I'll leave some comments on it...
see #108

Refactor react redux

---

app/app.jsx
app/components/goals-list/goals-list.jsx
app/components/nav.jsx
app/containers/main.jsx
app/main.js
package.json

@emilyb7 yo this seems to be working. I have left some comments. Do you want to review and ask questions?

Goals list setup fixes

---

.gitignore
.travis.yml
package.json

Sets up travis, adds .yml file

---

app/action_types.js
app/actions/add-new-goal.js
app/avatars.js
app/components/add-new-goal/add-new-goal.jsx
app/components/add-new-goal/new-goal-avatars.jsx
app/components/add-new-goal/new-goal-input.jsx
app/containers/main-container.jsx
app/reducers/index.js
app/scss/_general.scss
app/scss/_new-goal-avatars.scss

- Refactors the avatars component to be a controlled component
- Selected avatar is shown using blue border
- new goal is added to goals array in app state
- user redirected back to goals list
- goal shown in list

Save new goal

---

.babelrc
app/containers/main-container.jsx
app/reducers/index.js
package.json
tests/reducer-test.js
webpack.config.js

- adds tests for redux reducer
- installs babel-tape-runner
- bit of general tidying up!

Test reducer

---

app/action_types.js
app/actions/add-new-goal.js
app/components/add-new-goal/add-new-goal.jsx
app/components/add-new-goal/confirmation.jsx
app/containers/main-container.jsx
app/reducers/index.js
app/router.js
app/scss/_add-new-goal.scss
app/scss/_colors.scss
app/scss/_general.scss
app/scss/_menu.scss
tests/reducer-test.js

@shiryz check it out - add goal confirmation
i failed to do the animation, we might have to leave that unless we have extra time!

Add goal confirmation modal

---

app/components/feedback/feedback.jsx
app/components/goal-tile.jsx
app/scss/_feedback.scss

plus a few tidy-ups!
fixes #228

current score shown in goal tile on feedback page

---

public/styles/style.css

style fixes - login button

---

app/components/view-goal/line-chart.jsx
app/scss/_line-chart-detail.scss

Relatively superficial improvements to the line chart, as detailed in #243

Line chart improvements

---

app/components/rate-goal/animations/cactus.jsx
app/components/rate-goal/rate-goal-slider.jsx

makes animation slightly faster
also tidies up code a bit
related #183

small improvements to cactus animation

---

public/login.html
public/styles/style.css

fixes height of body and positioning of background image, fixes #270

Login page fixes for mobile

---

app/sockets.js
server/database/get-user-data.js
server/helpers/format-user-data.js
server/socket-manager.js

issues resolved within #250 caused some new issues, where user_id wasn't being set properly and goals were being created without a user...
'goals' event listener now registered only if authentication is successful
auth-success response sent to client independently of whether DB is able to retrieve user's goals (outside of callback belonging to DB function)
Edit: just added in #283

Fix authentication problems (please check first! 🙈)

---

README.md

Update app link to heroku link

---

app/actions/edit-goal.js
app/components/add-new-goal/new-goal-input.jsx
app/components/edit-goal/edit-goal.jsx
app/components/goal-tile.jsx
app/reducers/index.js
app/router.js
app/scss/_goalTile.scss

- fixes styling issues with edit and delete buttons, see #294 
- hides edit and delete containers when returning to goals list from another view / clicking on the nav bar
- css transition animation on edit and delete buttons
- input box for editing goal is prefilled with current goal title
all related #294

Edit delete optimisations

---

app/app.jsx
app/components/add-new-goal/add-new-goal.jsx
app/components/add-new-goal/new-goal-input.jsx
app/components/feedback/feedback-input.jsx
app/components/feedback/feedback.jsx
app/components/rate-goal/rate-goal.jsx
app/components/view-goal/line-chart-detail.jsx
app/components/view-goal/view-goal.jsx
app/containers/main-container.jsx
app/main.js
app/reducers/index.js
app/router.js
app/scss/_general.scss
app/scss/_goalTile.scss
app/scss/_goals-list.scss
app/scss/style.scss

Makes things look generally less terrible

More mobile fixes

---

.eslintignore
.eslintrc.js
app/sockets.js
package.json
server/database/db_build.js
server/database/db_connection.js
server/database/get-user-data.js
server/database/handle-goal-data.js
server/server.js
server/socket-manager.js
server/sockets.js
server/start-server.js
tests/reducer-test.js
tests/server-test.js
webpack.config.js

Finally added in linter as precommit hook, resolves #307

Eslint precommit

---

server/database/db_build.sql

Fixes #275 .
Adds foreign key constraints and changes date from time stamp to text.

Reformat database

---

docs/aws.md

adds document explaining AWS setup

---

.ebextensions/nodecommand.config

adds .ebextensions file for setting default node command as in AWS docs

---

package-lock.json

package lock for newest npm version

adds pack-lock file

---

README.md

updates the readme with notes on AWS deployment steps
